language: python

sudo: false

python:
  - "2.7"

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - netcdf-bin
      - libnetcdf-dev

install:
  - "pip install tox"
  - "pip install -r test-requirements.txt"

script: tox
